apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /pv0002
    server: 10.193.10.56
  persistentVolumeReclaimPolicy: Recycle

